MvcHomework3/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHomework3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contacts = new HashSet<Contact>();
            this.Banks = new HashSet<Bank>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string EIN { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime BD { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Bank> Banks { get; set; }
    }
}

MvcHomework3/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcHomework3.Models;

namespace MvcHomework3.Controllers
{
    public class BankController : Controller
    {
        //private CustomerEntities db = new CustomerEntities();
        private BankRepository repo = RepositoryHelper.GetBankRepository();
        private CustomerRepository customerRepo;
        public BankController()
        {
            customerRepo = RepositoryHelper.GetCustomerRepository(repo.UnitOfWork);
        }

        // GET: /Bank/
        public ActionResult Index()
        {
            var banks = //db.Banks.Include(b => b.Customer);
                repo.All().Include(b => b.Customer);
            return View(banks.ToList());
        }

        // GET: /Bank/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bank bank = //db.Banks.Find(id);
                repo.All().SingleOrDefault(b => b.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }
            return View(bank);
        }

        // GET: /Bank/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(/*db.Customers*/ customerRepo.All() , "Id", "Name");
            return View();
        }

        // POST: /Bank/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,CustomerId,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] Bank bank)
        {
            if (ModelState.IsValid)
            {
                //db.Banks.Add(bank);
                //db.SaveChanges();
                repo.Add(bank);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(/*db.Customers*/ customerRepo.All(), "Id", "Name", bank.CustomerId);
            return View(bank);
        }

        // GET: /Bank/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bank bank = //db.Banks.Find(id);
                repo.All().SingleOrDefault(b => b.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(/*db.Customers*/ customerRepo.All(), "Id", "Name", bank.CustomerId);
            return View(bank);
        }

        // POST: /Bank/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,CustomerId,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] BankUpdateVM bank)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(bank).State = EntityState.Modified;
                //db.SaveChanges();
                var updated = repo.All().FirstOrDefault(b => b.Id == bank.Id);
                AutoMapper.Mapper.DynamicMap<BankUpdateVM, Bank>(bank, updated);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(/*db.Customers*/ customerRepo.All(), "Id", "Name", bank.CustomerId);
            return View(bank);
        }

        // GET: /Bank/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bank bank = //db.Banks.Find(id);
                repo.All().SingleOrDefault(b => b.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }
            return View(bank);
        }

        // POST: /Bank/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bank bank = //db.Banks.Find(id);
                repo.All().SingleOrDefault(b => b.Id == id);
            //db.Banks.Remove(bank);
            //db.SaveChanges();
            repo.Delete(bank);
            repo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
                repo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcHomework3/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcHomework3.Models;
using System.IO;
using System.Text;

namespace MvcHomework3.Controllers
{
    //[CheckIdFilter]
    public class CustomerController : BaseController
    {
        //private CustomerEntities db = new CustomerEntities();
        private CustomerRepository repo;
        private ContactRepository contactRepo;
        private BankRepository bankRepo;

        public CustomerController()
        {
            repo = RepositoryHelper.GetCustomerRepository();
            contactRepo = RepositoryHelper.GetContactRepository(repo.UnitOfWork);
            bankRepo = RepositoryHelper.GetBankRepository(repo.UnitOfWork);
        }

        public ActionResult Download()
        {
            string csv = CreateCSVTextFile(repo.All().ToList());
            return File(ASCIIEncoding.GetEncoding("big5").GetBytes(csv), "text/csv",
                string.Format("{0}_客戶資料匯出.csv", DateTime.Now.ToString("yyyyMMdd")));
        }

        // http://stackoverflow.com/a/17698392/823247
        private string CreateCSVTextFile<T>(List<T> data)
        {
            var properties = typeof(T).GetProperties();
            var result = new StringBuilder();

            foreach (var row in data)
            {
                var values = properties.Select(p => p.GetValue(row, null))
                                       .Select(v => StringToCSVCell(Convert.ToString(v)));
                var line = string.Join(",", values);
                result.AppendLine(line);
            }

            return result.ToString();
        }

        private string StringToCSVCell(string str)
        {
            bool mustQuote = (str.Contains(",") || str.Contains("\"") || str.Contains("\r") || str.Contains("\n"));
            if (mustQuote)
            {
                StringBuilder sb = new StringBuilder();
                sb.Append("\"");
                foreach (char nextChar in str)
                {
                    sb.Append(nextChar);
                    if (nextChar == '"')
                        sb.Append("\"");
                }
                sb.Append("\"");
                return sb.ToString();
            }

            return str;
        }

        // GET: /Customer/
        public ActionResult Index()
        {
            return View(repo.All());
        }

        // GET: /Customer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = repo.All().SingleOrDefault(i => i.Id == id); //db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }

            //ViewBag.Contacts = customer.Contacts.ToList();
            //ViewBag.Banks = customer.Banks.ToList();

            return View(customer);
        }

        // GET: /Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,EIN,Phone,Fax,Address,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                //db.Customers.Add(customer);
                //db.SaveChanges();
                repo.Add(customer);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: /Customer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = repo.All().SingleOrDefault(i => i.Id == id); //db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }

            //AutoMapper.Mapper.DynamicMap<List<Contact>, List<ContactUpdateVM>>(customer.Contacts.ToList(), contactVMList);
            AutoMapper.Mapper.CreateMap<Contact, ContactUpdateVM>();
            List<ContactUpdateVM> contactVMList = AutoMapper.Mapper.Map<List<Contact>, List<ContactUpdateVM>>(customer.Contacts.ToList());
            ViewBag.Contacts = contactVMList;

            AutoMapper.Mapper.CreateMap<Bank, BankUpdateVM>();
            List<BankUpdateVM> bankVMList = AutoMapper.Mapper.Map<List<Bank>, List<BankUpdateVM>>(customer.Banks.ToList());

            ViewBag.Banks = //customer.Banks.ToList();
                //AutoMapper.Mapper.DynamicMap<List<BankUpdateVM>>(customer.Banks.ToList());
                bankVMList;

            return View(AutoMapper.Mapper.DynamicMap<CustomerUpdateVM>(customer));
        }

        // POST: /Customer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(//[Bind(Include = "Id,Name,EIN,Phone,Fax,Address,Email")] 
            CustomerUpdateVM customer,
            List<ContactUpdateVM> contacts,
            List<BankUpdateVM> banks)
        {
            if (TryUpdateModel(customer) && ModelState.IsValid)
            {
                //db.Entry(customer).State = EntityState.Modified;
                //db.SaveChanges();
                var updated = repo.All().SingleOrDefault(i => i.Id == customer.Id);
                //updated.Name = customer.Name;
                //updated.EIN = customer.EIN;
                //updated.Phone = customer.Phone;
                //updated.Fax = customer.Fax;
                //updated.Address = customer.Address;
                //updated.Email = customer.Email;
                AutoMapper.Mapper.DynamicMap<CustomerUpdateVM, Customer>(customer, updated);

                // update contacts
                foreach (var item in contacts)
                {
                    //if (TryUpdateModel(item))
                    //{
                        var updatedItem = contactRepo.All().SingleOrDefault(i => i.Id == item.Id);
                        //updatedContact.Title = item.Title;
                        //updatedContact.Name = item.Name;
                        //updatedContact.Email = item.Email;
                        //updatedContact.Mobile = item.Mobile;
                        //updatedContact.Phone = item.Phone;
                        AutoMapper.Mapper.DynamicMap<ContactUpdateVM, Contact>(item, updatedItem);
                    //}
                }

                // update banks
                foreach(var item in banks)
                {
                    var updatedItem = bankRepo.All().SingleOrDefault(i => i.Id == item.Id);
                    AutoMapper.Mapper.DynamicMap<BankUpdateVM, Bank>(item, updatedItem);
                }

                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.Contacts = contacts;
            ViewBag.Banks = banks;
            return View(customer);
        }

        // GET: /Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = repo.All().SingleOrDefault(i => i.Id == id); //db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: /Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = repo.All().SingleOrDefault(i => i.Id == id); //db.Customers.Find(id);
            repo.Delete(customer); //db.Customers.Remove(customer);
            repo.UnitOfWork.Commit(); //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repo.UnitOfWork.Context.Dispose(); //db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult BankList(int id)
        {
            var data = bankRepo.All().Where(b => b.CustomerId == id).ToList();
            return PartialView(data);
        }

        public ActionResult ContactList(int id)
        {
            var data = contactRepo.All().Where(c => c.CustomerId == id).ToList();
            return PartialView(data);
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            //file.SaveAs(file.FileName); //### don't! in ie, this will be full path on client
            var fileName = Path.GetFileName(file.FileName);
            file.SaveAs(Server.MapPath("~/App_Data/" + fileName));
            return View();
        }
    }
}

MvcHomework3/Views/Customer/BankList.cshtml
@model List<MvcHomework3.Models.Bank>

<h5>Banks</h5>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().銀行名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().銀行代碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().分行代碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().帳戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().帳戶號碼)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.銀行名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.銀行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.分行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶號碼)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "Bank", new { id = item.Id }, "")
            </td>
        </tr>
    }

</table>


MvcHomework3/Views/Customer/ContactList.cshtml
@model List<MvcHomework3.Models.Contact>
<h5>Contacts</h5>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Mobile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Phone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "Contact", new { id = item.Id }, "")
            </td>
        </tr>
    }

</table>

MvcHomework3/Views/Customer/Create.cshtml
@model MvcHomework3.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EIN, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EIN)
                @Html.ValidationMessageFor(model => model.EIN)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax)
                @Html.ValidationMessageFor(model => model.Fax)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcHomework3/Views/Customer/Delete.cshtml
@model MvcHomework3.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcHomework3/Views/Customer/Edit.cshtml
@model MvcHomework3.Models.CustomerUpdateVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EIN, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EIN)
                @Html.ValidationMessageFor(model => model.EIN)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax)
                @Html.ValidationMessageFor(model => model.Fax)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BD, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BD)
                @Html.ValidationMessageFor(model => model.BD)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

        <div>
            <h5>Contacts</h5>
            <p>
                @Html.ActionLink("Create New", "Create", "Contact")
            </p>
            @{ var contacts = ViewBag.Contacts as List<MvcHomework3.Models.ContactUpdateVM>; }
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => contacts.FirstOrDefault().Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => contacts.FirstOrDefault().Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => contacts.FirstOrDefault().Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => contacts.FirstOrDefault().Mobile)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => contacts.FirstOrDefault().Phone)
                    </th>
                    <th></th>
                </tr>
                
                @for(int i = 0; i< contacts.Count;i++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(modelItem => contacts[i].Id)
                            @Html.HiddenFor(modelItem => contacts[i].CustomerId)
                            @Html.EditorFor(modelItem => contacts[i].Title)
                            @Html.ValidationMessageFor(modelItem => contacts[i].Title)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => contacts[i].Name)
                            @Html.ValidationMessageFor(modelItem => contacts[i].Name)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => contacts[i].Email)
                            @Html.ValidationMessageFor(modelItem => contacts[i].Email)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => contacts[i].Mobile)
                            @Html.ValidationMessageFor(modelItem => contacts[i].Mobile)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => contacts[i].Phone)
                            @Html.ValidationMessageFor(modelItem => contacts[i].Phone)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Contact", new { id = contacts[i].Id }, "") |
                            @Html.ActionLink("Details", "Details", "Contact", new { id = contacts[i].Id }, "") |
                            @Html.ActionLink("Delete", "Delete", "Contact", new { id = contacts[i].Id }, "")
                        </td>
                    </tr>
                }

            </table>
            <h5>Banks</h5>
            <p>
                @Html.ActionLink("Create New", "Create", "Bank")
            </p>
            @{ var banks = ViewBag.Banks as List<MvcHomework3.Models.BankUpdateVM>; }
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => banks.FirstOrDefault().銀行名稱)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => banks.FirstOrDefault().銀行代碼)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => banks.FirstOrDefault().分行代碼)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => banks.FirstOrDefault().帳戶名稱)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => banks.FirstOrDefault().帳戶號碼)
                    </th>
                    <th></th>
                </tr>
                
                @for (int i = 0; i < banks.Count; i++ )
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(m => banks[i].Id)
                            @Html.HiddenFor(m=>banks[i].CustomerId)
                            @Html.EditorFor(modelItem => banks[i].銀行名稱)
                            @Html.ValidationMessageFor(modelItem => banks[i].銀行名稱)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => banks[i].銀行代碼)
                            @Html.ValidationMessageFor(modelItem => banks[i].銀行代碼)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => banks[i].分行代碼)
                            @Html.ValidationMessageFor(modelItem => banks[i].分行代碼)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => banks[i].帳戶名稱)
                            @Html.ValidationMessageFor(modelItem => banks[i].帳戶名稱)
                        </td>
                        <td>
                            @Html.EditorFor(modelItem => banks[i].帳戶號碼)
                            @Html.ValidationMessageFor(modelItem => banks[i].帳戶號碼)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Bank", new { id = banks[i].Id }, "") |
                            @Html.ActionLink("Details", "Details", "Bank", new { id = banks[i].Id }, "") |
                            @Html.ActionLink("Delete", "Delete", "Bank", new { id = banks[i].Id }, "")
                        </td>
                    </tr>
                }

            </table>
        </div>

        
    </div>
    
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}